# Generated by Django 4.2.10 on 2024-02-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_bookuserrelation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuserrelation',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
