# Generated by Django 4.2.10 on 2024-03-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_bookuserrelation_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuserrelation',
            name='discount',
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
