# Generated by Django 4.2.10 on 2024-03-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_bookuserrelation_discount_book_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
